#!/bin/sh
### BEGIN INIT INFO
# Provides:          halt
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0
# Short-Description: Execute the halt command.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin


hddown="-h"

halt SED_HALTARGS -p $hddown

: exit 0
